name: 'Run standardrb with reviewdog'
description: '🐶 Run standardrb with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  rubocop_flags:
    description: 'standardrb flags. (standardrb <rubocop_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'standardrb'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  rubocop_version:
    description: 'Rubocop version'
  standard_version:
    description: 'Standard version'
  rubocop_extensions:
    description: 'Rubocop extensions'
    default: 'rubocop-rails rubocop-performance rubocop-rspec rubocop-i18n rubocop-rake'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `true`.
    default: 'true'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: v0.15.0
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_RUBOCOP_FLAGS: ${{ inputs.rubocop_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_RUBOCOP_VERSION: ${{ inputs.rubocop_version }}
        INPUT_STANDARD_VERSION: ${{ inputs.standard_version }}
        INPUT_RUBOCOP_EXTENSIONS: ${{ inputs.rubocop_extensions }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
branding:
  icon: 'check-circle'
  color: 'red'
